ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=99000]
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: sort-simple-yaml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: debug-statements
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: requirements-txt-fixer
  - id: check-executables-have-shebangs
  - id: check-ast

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade

- repo: https://github.com/dhruvmanila/remove-print-statements
  rev: v0.5.2     # Replace with latest tag on GitHub
  hooks:
  - id: remove-print-statements
    types: [python]
    args: [--verbose]         # Show all the print statements to be removed

- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    args: [--remove-unused-variables, --remove-all-unused-imports]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile, black]

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.7
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]

- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort
    name: toml-sort
    entry: toml-sort
    args: [--check]
    language: python
    types: [toml]
  - id: toml-sort-fix
    name: toml-sort-fix
    entry: toml-sort
    args: [--in-place]
    language: python
    types: [toml]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    name: Pretty format TOML
    description: This hook sets a standard for formatting TOML files.
    entry: pretty-format-toml
    language: python
    types: [toml]
    minimum_pre_commit_version: '1'
    args: [--autofix]
  - id: pretty-format-yaml
    name: Pretty format YAML
    description: This hook sets a standard for formatting YAML files.
    entry: pretty-format-yaml
    language: python
    types: [yaml]
    minimum_pre_commit_version: '1'
    args: [--autofix, --indent, '2']

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
    args: [--shell=bash]      # Adjust this if you're using a different shell

- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.7.0-4
  hooks:
      # Choose one of:
  - id: shfmt             # native (requires/installs Go to build)

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    exclude: '[a-zA-Z]*/(migrations)/(.)*'
    types: [python]
    args: [-rn, -sn, --rcfile=pyproject.toml]
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true


- repo: https://github.com/pycqa/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: [-iii, -ll]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-mutable, flake8-print, flake8-simplify]
