import networkx as nx

SEED = None

collection_small = [ 
    nx.random_graphs.erdos_renyi_graph(10, 0.5, seed=SEED),
    nx.random_graphs.barabasi_albert_graph(10, 3, seed=SEED),
    nx.random_graphs.random_regular_graph(3, 10, seed=SEED),
    nx.random_graphs.random_powerlaw_tree(10, seed=SEED),
]

# collection_public = [ 
#     nx.random_graphs.erdos_renyi_graph(10, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(10, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(10, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(10, 0.3, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(10, 0.2, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(50, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(50, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(50, 0.2, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(50, 0.8, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.3, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.2, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(100, 0.5, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(200, 0.2, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(200, 0.1, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(1000, 0.1, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(1000, 0.8, seed=SEED),
#     nx.random_graphs.erdos_renyi_graph(1000, 0.8, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(10, 20, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(10, 20, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(10, 30, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(100, 60, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(100, 300, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(100, 300, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(100, 2000, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(100, 3000, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(1000, 3000, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(1000, 500000, seed=SEED),
#     nx.random_graphs.dense_gnm_random_graph(1000, 400000, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(10, 3, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(10, 3, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(10, 5, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(100, 3, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(100, 50, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(100, 70, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(1000, 30, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(1000, 100, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(1000, 300, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(1000, 500, seed=SEED),
#     nx.random_graphs.barabasi_albert_graph(1000, 500, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 10, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 10, seed=SEED),
#     nx.random_graphs.random_regular_graph(5, 10, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(5, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(5, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(30, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(80, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(3, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(30, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(30, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(10, 200, seed=SEED),
#     nx.random_graphs.random_regular_graph(10, 200, seed=SEED),
#     nx.random_graphs.random_regular_graph(500, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(500, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(800, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(800, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(800, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(20, 100, seed=SEED),
#     nx.random_graphs.random_regular_graph(100, 1000, seed=SEED),
#     nx.random_graphs.random_regular_graph(10, 1000, seed=SEED),
#     nx.binomial_tree(10),
#     nx.binomial_tree(20),
#     nx.binomial_tree(100),
#     nx.binomial_tree(1000),
# ]

from functools import partial

collection_public = [ 
    partial(nx.wheel_graph, 10),
    partial(nx.complete_graph, 10),
    partial(nx.complete_graph, 100),
    partial(nx.random_graphs.erdos_renyi_graph, 10, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 10, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 10, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 10, 0.3, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 10, 0.2, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 50, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 50, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 50, 0.2, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 50, 0.8, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.3, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.2, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 100, 0.5, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 200, 0.2, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 200, 0.1, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 1000, 0.1, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 1000, 0.8, seed=SEED),
    partial(nx.random_graphs.erdos_renyi_graph, 1000, 0.8, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 10, 20, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 10, 20, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 10, 30, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 100, 60, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 100, 300, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 100, 300, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 100, 2000, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 100, 3000, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 1000, 3000, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 1000, 500000, seed=SEED),
    partial(nx.random_graphs.dense_gnm_random_graph, 1000, 400000, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 10, 3, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 10, 3, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 10, 5, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 100, 3, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 100, 50, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 100, 70, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 30, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 30, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 100, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 300, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 500, seed=SEED),
    partial(nx.random_graphs.barabasi_albert_graph, 1000, 500, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 10, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 10, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 5, 10, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 5, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 5, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 30, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 80, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 3, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 30, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 10, 200, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 10, 200, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 500, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 500, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 800, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 20, 100, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 100, 1000, seed=SEED),
    partial(nx.random_graphs.random_regular_graph, 10, 1000, seed=SEED),
    partial(nx.binomial_tree, 4),
    partial(nx.binomial_tree, 8),
    partial(nx.binomial_tree, 9),
]
